repos:
  # Code formatting and linting
  - repo: https://github.com/PyCQA/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: ["--profile", "black"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.6
    hooks:
      - id: ruff-format
      - id: ruff
        args: ["--fix", "--exit-non-zero-on-fix"]
        types_or: [python, pyi]
        require_serial: true

  # Security scanning - critical for our security cleanup initiative
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.10
    hooks:
      - id: bandit
        args: ["-c", ".bandit", "-r", "src/"]
        exclude: "tests/"
        types: [python]

  # Basic file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-ast
      - id: check-added-large-files

  # Optional: Enable mypy for critical modules
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.15.0
  #   hooks:
  #     - id: mypy
  #       args: ["--ignore-missing-imports"]
  #       additional_dependencies: ["types-pyyaml"]
  #       files: "^src/(pytest_analyzer/mcp|pytest_analyzer/core)/"

  # C/C++ formatting (keep existing)
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v20.1.0
    hooks:
      - id: clang-format
        files: "\\.(c|cpp|h|hpp|pyx)$"
