[project]
name = "pytest-analyzer"
version = "0.1.0"
description = "Analyzes pytest test results to identify patterns and suggest fixes."
authors = ["Your Name <your.email@example.com>"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]

[tasks]
dev = "pip install -e ."
install-editable = "pip install -e ."
lint = "ruff check src tests"
lint-fix = "ruff check --fix src tests"
format = "ruff format src tests"
typecheck = "mypy src tests"
test = "pytest tests"
test-cov = { cmd = "pytest --cov=src/pytest_analyzer --cov-report=term-missing --cov-report=xml tests", depends-on = ["install-editable"] }
build = { cmd = "hatch build", depends-on = ["install-editable"] }
clean = "rm -rf dist build .ruff_cache .mypy_cache .pytest_cache *.egg-info src/pytest_analyzer.egg-info"
check-all = { depends-on = ["lint", "typecheck", "test"] }
