[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pytest-analyzer"
dynamic = ["version"]
description = "Analyzes pytest test results to identify patterns and suggest fixes."
readme = "README.md"
requires-python = ">=3.9"
license = { text = "MIT" }
authors = [
    { name = "Memento", email = "claude.rc@gmail.com" },
]
keywords = ["pytest", "testing", "analysis", "reporting", "debugging"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Framework :: Pytest",
    "Topic :: Software Development :: Testing",
    "Topic :: Software Development :: Quality Assurance",
]

dependencies = [
    "PyYaml",
    "rich>=12.0.0",
    "types-PyYAML",
]

[project.optional-dependencies]
dev = [
    "black",
    "isort",
    "mkdocs",
    "mypy",
    "pre-commit",
    "ruff",
]

test = [
    "pytest>=7.0.0",
    "pytest-asyncio",
    "pytest-cov",
    "pytest-json-report>=1.5.0",
]

[project.scripts]
pytest-analyzer = "pytest_analyzer.cli.analyzer_cli:main"

[project.urls]
Homepage = "https://github.com/yourusername/pytest_analyzer"
Repository = "https://github.com/yourusername/pytest_analyzer"
Issues = "https://github.com/yourusername/pytest_analyzer/issues"

[tool.hatch.version]
path = "src/pytest_analyzer/__version__.py"

[tool.pixi]
package-dir = {"" = "src"}

[tool.pixi.build]
packages = ["src/pytest_analyzer"]

[tool.pytest.ini_options]
testpaths = ["tests"]
asyncio_default_fixture_loop_scope = "function"
log_cli = false
log_level = "WARNING"
filterwarnings = ["ignore::DeprecationWarning", "ignore::pytest.PytestDeprecationWarning"]
addopts = "--quiet"
