[project]
name = "pixi-example-project"
version = "0.1.0"
description = "A minimal Pixi project for pytest-analyzer detection."
authors = ["pytest-analyzer-example <example@example.com>"]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "win-64"]

[tasks]
test = "pytest"

[dependencies]
python = ">=3.9,<3.13"
pytest = ">=7.0"
