name: CI

on:
  push:
    branches: [main, development]
  pull_request:
    branches: [main, development]

jobs:
  lint_and_types:
    runs-on: ubuntu-latest
    # name: lint_and_type (${{ github.event_name }})

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: prefix-dev/setup-pixi@v0.8.12
        with:
          pixi-version: latest
          manifest-path: pyproject.toml

      - name: Install dependencies with Pixi
        run: pixi install -e dev -v

      - name: Install pre-commit hooks
        run: pixi run -e dev setup-pre-commit

      - name: Run pre-commit
        run: |
          pixi run -e dev pre-commit run --all-files
          if [ -n "$(git status --porcelain)" ]; then
            echo "::error::Code is not properly formatted. Please run formatters locally before pushing."
            git diff
            exit 1
          fi

  test:
    needs: lint_and_types
    runs-on: ${{ matrix.os }}
    # name: test-${{ matrix.python-version }} (${{ github.event_name }})
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9, 3.10, 3.11, 3.12]

    steps:
      - uses: actions/checkout@v5

      - uses: prefix-dev/setup-pixi@v0.8.12
        with:
          pixi-version: latest
          manifest-path: pyproject.toml

      - name: Install dependencies with Pixi
        run: pixi install -e dev -v

      - name: Run tests with coverage
        run: pixi run -e dev test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: coverage.xml
