name: CI

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  lint_and_type:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Pixi
        run: |
          curl -sSL https://pixi.sh/install.sh | bash
          export PATH="$HOME/.pixi/bin:$PATH"

      - name: Install dependencies with Pixi
        run: pixi install dev

      - name: Install pre-commit hooks
        run: pixi run pre-commit install --install-hooks

      - name: Run pre-commit
        run: pixi run pre-commit run --all-files

      - name: Check formatting with Black
        run: pixi run black --check .

      - name: Check import sorting with isort
        run: pixi run isort --check-only .

      - name: Lint with ruff
        run: pixi run ruff check .

      - name: Type check with mypy
        run: pixi run mypy src tests

  test:
    needs: lint_and_type
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.8, 3.9, 3.10, 3.11, 3.12]

    steps:
      - uses: actions/checkout@v3

      - name: Install Pixi
        run: |
          curl -sSL https://pixi.sh/install.sh | bash
          export PATH="$HOME/.pixi/bin:$PATH"

      - name: Install dependencies with Pixi
        run: pixi install test

      - name: Run tests with coverage
        run: pixi run pytest tests --quiet

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: coverage.xml
